# #Password for MariaDB Root user
mysql_root_password: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') | default('pwd_123456789', true) }}"
## WordPress-DatBase Name:
wordpress_db: "wordpress"
##Wordpress DataBase UserName:
wordpress_dbuser: "wordpress"
## WordPress DataBase Password
wordpress_dbpass: "{{ lookup('env', 'WORDPRESS_DB_PASSWORD') | default('wp_123456789', true) }}"
## WordPress Database localhost hostname
host: "localhost"
