galaxy_info:
  author: your name
  description: WordPress Ansible Role for EL9 and Ubuntu 24.04
  company: your company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - wordpress
    - apache
    - php
    - mysql
dependencies: []
